services:
  - type: web
    name: bilgelojistik-api
    runtime: docker
    rootDir: backend/BilgeLojistikIK.API
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: bilgelojistik-db
          property: connectionString
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: BilgeLojistikIK
      - key: Jwt__ExpireHours
        value: 8
      - key: FRONTEND_URL
        value: https://bilgelojistik-ik.vercel.app

databases:
  - name: bilgelojistik-db
    databaseName: bilgelojistikikdb
    user: bilgelojistik
    plan: free
